package types

type ENVIRONMENT_TYPES int32

const (
	ENVIRONMENT_TYPES_UNSPECIFIED  ENVIRONMENT_TYPES = 0
	ENVIRONMENT_TYPES_LOCAL        ENVIRONMENT_TYPES = 1
	ENVIRONMENT_TYPES_REMOTE       ENVIRONMENT_TYPES = 2
	ENVIRONMENT_TYPES_DOCKER       ENVIRONMENT_TYPES = 3
	ENVIRONMENT_TYPES_KUBERNETES   ENVIRONMENT_TYPES = 4
	ENVIRONMENT_TYPES_UNRECOGNIZED ENVIRONMENT_TYPES = 5
)

// Enum value maps for ENVIRONMENT_TYPES.
var (
	ENVIRONMENT_TYPES_name = map[int32]string{
		0: "ENVIRONMENT_TYPES_UNSPECIFIED",
		1: "ENVIRONMENT_TYPES_LOCAL",
		2: "ENVIRONMENT_TYPES_REMOTE",
		3: "ENVIRONMENT_TYPES_DOCKER",
		4: "ENVIRONMENT_TYPES_KUBERNETES",
		5: "ENVIRONMENT_TYPES_UNRECOGNIZED",
	}
	ENVIRONMENT_TYPES_value = map[string]int32{
		"ENVIRONMENT_TYPES_UNSPECIFIED":  0,
		"ENVIRONMENT_TYPES_LOCAL":        1,
		"ENVIRONMENT_TYPES_REMOTE":       2,
		"ENVIRONMENT_TYPES_DOCKER":       3,
		"ENVIRONMENT_TYPES_KUBERNETES":   4,
		"ENVIRONMENT_TYPES_UNRECOGNIZED": 5,
	}
)

func (x ENVIRONMENT_TYPES) Enum() *ENVIRONMENT_TYPES {
	p := new(ENVIRONMENT_TYPES)
	*p = x
	return p
}
