package types

type RECIPIENT_TYPES int32

const (
	RECIPIENT_TYPES_UNSPECIFIED  RECIPIENT_TYPES = 0
	RECIPIENT_TYPES_SERVER       RECIPIENT_TYPES = 1
	RECIPIENT_TYPES_CLIENT       RECIPIENT_TYPES = 2
	RECIPIENT_TYPES_INDIVIDUAL   RECIPIENT_TYPES = 3
	RECIPIENT_TYPES_GROUP        RECIPIENT_TYPES = 4
	RECIPIENT_TYPES_UNRECOGNIZED RECIPIENT_TYPES = 5
)

// Enum value maps for RECIPIENT_TYPES.
var (
	RECIPIENT_TYPES_name = map[int32]string{
		0: "RECIPIENT_TYPES_UNSPECIFIED",
		1: "RECIPIENT_TYPES_SERVER",
		2: "RECIPIENT_TYPES_CLIENT",
		3: "RECIPIENT_TYPES_INDIVIDUAL",
		4: "RECIPIENT_TYPES_GROUP",
		5: "RECIPIENT_TYPES_UNRECOGNIZED",
	}
	RECIPIENT_TYPES_value = map[string]int32{
		"RECIPIENT_TYPES_UNSPECIFIED":  0,
		"RECIPIENT_TYPES_SERVER":       1,
		"RECIPIENT_TYPES_CLIENT":       2,
		"RECIPIENT_TYPES_INDIVIDUAL":   3,
		"RECIPIENT_TYPES_GROUP":        4,
		"RECIPIENT_TYPES_UNRECOGNIZED": 5,
	}
)

func (x RECIPIENT_TYPES) Enum() *RECIPIENT_TYPES {
	p := new(RECIPIENT_TYPES)
	*p = x
	return p
}
