package types

type STAGE_TYPES int32

const (
	STAGE_TYPES_UNSPECIFIED  STAGE_TYPES = 0
	STAGE_TYPES_DEVELOPMENT  STAGE_TYPES = 1
	STAGE_TYPES_STAGING      STAGE_TYPES = 2
	STAGE_TYPES_PRODUCTION   STAGE_TYPES = 3
	STAGE_TYPES_UNRECOGNIZED STAGE_TYPES = 4
)

// Enum value maps for STAGE_TYPES.
var (
	STAGE_TYPES_name = map[int32]string{
		0: "STAGE_TYPES_UNSPECIFIED",
		1: "STAGE_TYPES_DEVELOPMENT",
		2: "STAGE_TYPES_STAGING",
		3: "STAGE_TYPES_PRODUCTION",
		4: "STAGE_TYPES_UNRECOGNIZED",
	}
	STAGE_TYPES_value = map[string]int32{
		"STAGE_TYPES_UNSPECIFIED":  0,
		"STAGE_TYPES_DEVELOPMENT":  1,
		"STAGE_TYPES_STAGING":      2,
		"STAGE_TYPES_PRODUCTION":   3,
		"STAGE_TYPES_UNRECOGNIZED": 4,
	}
)

func (x STAGE_TYPES) Enum() *STAGE_TYPES {
	p := new(STAGE_TYPES)
	*p = x
	return p
}
