package types

type GENERAL_STATE_TYPES int32

const (
	GENERAL_STATE_TYPES_UNSPECIFIED  GENERAL_STATE_TYPES = 0
	GENERAL_STATE_TYPES_DISABLED     GENERAL_STATE_TYPES = 1
	GENERAL_STATE_TYPES_ENABLED      GENERAL_STATE_TYPES = 2
	GENERAL_STATE_TYPES_INACTIVE     GENERAL_STATE_TYPES = 3
	GENERAL_STATE_TYPES_ACTIVE       GENERAL_STATE_TYPES = 4
	GENERAL_STATE_TYPES_DISCONNECTED GENERAL_STATE_TYPES = 5
	GENERAL_STATE_TYPES_CONNECTED    GENERAL_STATE_TYPES = 6
	GENERAL_STATE_TYPES_UNREGISTERED GENERAL_STATE_TYPES = 7
	GENERAL_STATE_TYPES_REGISTERED   GENERAL_STATE_TYPES = 8
	GENERAL_STATE_TYPES_UNSUBSCRIBED GENERAL_STATE_TYPES = 9
	GENERAL_STATE_TYPES_SUBSCRIBED   GENERAL_STATE_TYPES = 10
	GENERAL_STATE_TYPES_UNAUTHORIZED GENERAL_STATE_TYPES = 11
	GENERAL_STATE_TYPES_AUTHORIZED   GENERAL_STATE_TYPES = 12
	GENERAL_STATE_TYPES_UNCONFIRMED  GENERAL_STATE_TYPES = 13
	GENERAL_STATE_TYPES_CONFIRMED    GENERAL_STATE_TYPES = 14
	GENERAL_STATE_TYPES_UNVERIFIED   GENERAL_STATE_TYPES = 15
	GENERAL_STATE_TYPES_VERIFIED     GENERAL_STATE_TYPES = 16
	GENERAL_STATE_TYPES_UNAPPROVED   GENERAL_STATE_TYPES = 17
	GENERAL_STATE_TYPES_APPROVED     GENERAL_STATE_TYPES = 18
	GENERAL_STATE_TYPES_UNFINISHED   GENERAL_STATE_TYPES = 19
	GENERAL_STATE_TYPES_FINISHED     GENERAL_STATE_TYPES = 20
	GENERAL_STATE_TYPES_UNRECOGNIZED GENERAL_STATE_TYPES = 21
)

var GENERAL_STATE_TYPES_name = map[int32]string{
	0:  "GENERAL_STATE_TYPES_UNSPECIFIED",
	1:  "GENERAL_STATE_TYPES_DISABLED",
	2:  "GENERAL_STATE_TYPES_ENABLED",
	3:  "GENERAL_STATE_TYPES_INACTIVE",
	4:  "GENERAL_STATE_TYPES_ACTIVE",
	5:  "GENERAL_STATE_TYPES_DISCONNECTED",
	6:  "GENERAL_STATE_TYPES_CONNECTED",
	7:  "GENERAL_STATE_TYPES_UNREGISTERED",
	8:  "GENERAL_STATE_TYPES_REGISTERED",
	9:  "GENERAL_STATE_TYPES_UNSUBSCRIBED",
	10: "GENERAL_STATE_TYPES_SUBSCRIBED",
	11: "GENERAL_STATE_TYPES_UNAUTHORIZED",
	12: "GENERAL_STATE_TYPES_AUTHORIZED",
	13: "GENERAL_STATE_TYPES_UNCONFIRMED",
	14: "GENERAL_STATE_TYPES_CONFIRMED",
	15: "GENERAL_STATE_TYPES_UNVERIFIED",
	16: "GENERAL_STATE_TYPES_VERIFIED",
	17: "GENERAL_STATE_TYPES_UNAPPROVED",
	18: "GENERAL_STATE_TYPES_APPROVED",
	19: "GENERAL_STATE_TYPES_UNFINISHED",
	20: "GENERAL_STATE_TYPES_FINISHED",
	21: "GENERAL_STATE_TYPES_UNRECOGNIZED",
}

var GENERAL_STATE_TYPES_value = map[string]int32{
	"GENERAL_STATE_TYPES_UNSPECIFIED":  0,
	"GENERAL_STATE_TYPES_DISABLED":     1,
	"GENERAL_STATE_TYPES_ENABLED":      2,
	"GENERAL_STATE_TYPES_INACTIVE":     3,
	"GENERAL_STATE_TYPES_ACTIVE":       4,
	"GENERAL_STATE_TYPES_DISCONNECTED": 5,
	"GENERAL_STATE_TYPES_CONNECTED":    6,
	"GENERAL_STATE_TYPES_UNREGISTERED": 7,
	"GENERAL_STATE_TYPES_REGISTERED":   8,
	"GENERAL_STATE_TYPES_UNSUBSCRIBED": 9,
	"GENERAL_STATE_TYPES_SUBSCRIBED":   10,
	"GENERAL_STATE_TYPES_UNAUTHORIZED": 11,
	"GENERAL_STATE_TYPES_AUTHORIZED":   12,
	"GENERAL_STATE_TYPES_UNCONFIRMED":  13,
	"GENERAL_STATE_TYPES_CONFIRMED":    14,
	"GENERAL_STATE_TYPES_UNVERIFIED":   15,
	"GENERAL_STATE_TYPES_VERIFIED":     16,
	"GENERAL_STATE_TYPES_UNAPPROVED":   17,
	"GENERAL_STATE_TYPES_APPROVED":     18,
	"GENERAL_STATE_TYPES_UNFINISHED":   19,
	"GENERAL_STATE_TYPES_FINISHED":     20,
	"GENERAL_STATE_TYPES_UNRECOGNIZED": 21,
}

func (x GENERAL_STATE_TYPES) Enum() *GENERAL_STATE_TYPES {
	p := new(GENERAL_STATE_TYPES)
	*p = x
	return p
}
